spring:
  application:
    name: course-microservice
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.postgresql.Driver
    password: postgres
    url: jdbc:postgresql://localhost:5432/ct1courses
    username: postgres
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml


jwt:
  secret: G4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0G4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0
#  lifetime: 450000
#custom:
#  param: Hello world

server:
  port: 8082